name: Deploy Docs
description: Build and deploy documentation using mkdocs gh-deploy

inputs:
  github-token:
    description: GitHub token for pushing to gh-pages
    required: true

runs:
  using: composite
  steps:
    - uses: astral-sh/setup-uv@v7

    - name: Configure git
      shell: bash
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git remote set-url origin https://x-access-token:${{ inputs.github-token }}@github.com/${{ github.repository }}.git

    - name: Deploy docs
      shell: bash
      run: |
        uvx --with mkdocs-material --with pymdown-extensions mkdocs gh-deploy --force
