name: Deploy Versioned Docs
description: Deploy documentation using mike for version management

inputs:
  version:
    description: Version to deploy (e.g., "0.1.8")
    required: true
  github-token:
    description: GitHub token for pushing to gh-pages
    required: true

runs:
  using: composite
  steps:
    - uses: astral-sh/setup-uv@v7

    - name: Configure git
      shell: bash
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git remote set-url origin https://x-access-token:${{ inputs.github-token }}@github.com/${{ github.repository }}.git

    - name: Deploy with mike
      shell: bash
      run: |
        uvx --with mkdocs-material --with pymdown-extensions mike deploy --push --update-aliases "${{ inputs.version }}" latest
        uvx --with mkdocs-material --with pymdown-extensions mike set-default --push latest
